name: Deploy elm app

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: justgook/setup-elm@1.2.0
      - run:  elm make .\src\Main.elm --optimize --output=build/index.html
      - uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch