name: Deploy elm app

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Elm
        uses: justgook/setup-elm@1.2.0
        run: elm make src/Main.elm