- name: Deploy AWS Lambda function
  uses: yvesgurcan/deploy-lambda-function@v0.0.5

on:
  push:
    branches:
    - master

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: zip lambda.zip /functions/wordlist.txt lambda_function.py
      - uses: yvesgurcan/deploy-lambda-function
        with:
          package: lambda.zip
          function-name: findGlueWords
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}